version: "3.9"

services:
  nginx:
    container_name: zantt-nginx
    image: nginx:latest
    restart: always
    ports:
      - "80:80/tcp"
    volumes:
      - ./nginx-proxy-conf/zantt-local.conf:/etc/nginx/conf.d/default.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  mariadb:
    container_name: zantt-db
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: dnjem!1
    volumes:
      - ./db-data:/var/lib/mysql
    ports:
      - 3306:3306