server:
  port: 8899

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/zantt
    username: root
    password: dnjem!1
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update